# Generated by Django 3.1.1 on 2020-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('critique', 'critique'), ('danger', 'danger')], max_length=100, null=True)),
            ],
        ),
    ]
