# Generated by Django 3.1.1 on 2020-10-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_side', '0002_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sender',
        ),
    ]
