# Generated by Django 3.1.1 on 2020-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_side', '0005_auto_20201003_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Error', 'Error'), ('Warning', 'Warning'), ('Informational', 'Informational'), ('Debug', 'Debug')], help_text='type de rapport', max_length=100, null=True),
        ),
    ]
