"""
Django settings for my_pfe_2020 project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zpvwndqxpfbax9l8y&xe)+v_qxcw*io0o)%xf=dgycs9$3qpry'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# EMAIL_HOST = 'smtp.zoho.com'
# EMAIL_HOST_USER = 'ib5064939@gmail.com'
# EMAIL_HOST_PASSWORD = 'Zoho12345'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "ib5064939@gmail.com"
EMAIL_HOST_PASSWORD = "azertyx15"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pages',
    'reports_side',
    'authentication',
    'monitor_side',
    'django_extensions',
    'log_viewer',
    'configuration_side',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_pfe_2020.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_pfe_2020.wsgi.application'
ASGI_APPLICATION = 'my_pfe_2020.routing.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# my_pfe_DB sqlLite
# phpmyadmin my_pfe_db
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_pfe_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)

LOGGING ={
    'version':1,
    'loggers':{
        'django':{
            'handlers': ['file1', 'file2', 'file3', 'file4'],
            'level':'DEBUG'
        }
    },
    'handlers':{

        'file1':
            {
            'level':'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename':'./logs/debug.log',
            'maxBytes': 1024 * 1024 * 2,  # 10 MB
            # 'backupCount' : 1,
            'formatter': 'simpleRe',
            },
        'file2':
            {
            'level':'INFO',
            'class': 'logging.FileHandler',
            'filename':'./logs/info.log',
            'formatter': 'simpleRe',
            },
        'file3':
            {
            'level':'ERROR',
            'class': 'logging.FileHandler',
            'filename':'./logs/error.log',
            'formatter': 'simpleRe',
            },
        'file4':
            {
            'level':'WARNING',
            'class': 'logging.FileHandler',
            'filename':'./logs/warning.log',
            'formatter': 'simpleRe',
            },


    },
    'formatters':{
        'simpleRe': {
            'format': '{levelname} ( {asctime} ) : {message} [ {module} {process:d} {thread:d} ] ',
            'style': '{',
        }
}
}

