# Generated by Django 3.1.1 on 2020-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_side', '0002_auto_20201022_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_result',
            field=models.TextField(),
        ),
    ]
